# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - current
  workflow_dispatch:
    inputs:
      BUILD_BY:
        description: 'Builder identifier (e.g. jrandomhacker@example.net)'
        default: 'autobuild@vyos.net'
        required: true
      BUILD_VERSION:
        description: 'Version number (release builds only)'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume
      - uses: addnab/docker-run-action@v3
        with:
          registry: dockerhub
          image: vyos/vyos-build:current
          options: -v ${{ github.workspace }}:/vyos -w /vyos --privileged --sysctl net.ipv6.conf.lo.disable_ipv6=0 -e GOSU_UID=1006 -e GOSU_GID=1006
          run: |
            BUILD_BY=${{ github.event.inputs.BUILD_BY }}
            if [ -z $BUILD_BY ]; then
                BUILD_BY="autobuild@vyos.net"
            fi
            BUILD_VERSION=${{ github.event.inputs.BUILD_VERSION }}
            if [ -z $BUILD_VERSION ]; then
                BUILD_VERSION=$(date +%Y%m%d%H%M)
            fi
            git clone https://github.com/vyos/vyos-build
            cd vyos-build
            ./configure --build-by foo \
                        --debian-mirror http://ftp.us.debian.org/debian/ \
                        --build-type release --version ${BUILD_VERSION}
            sudo make iso
      - name: Upload VyOS ISO artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/*.iso
          asset_name: foo.iso
          asset_content_type: application/octet-stream
    
