# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - current
  workflow_dispatch:
    inputs:
      BUILD_BY:
        description: 'Builder identifier (e.g. jrandomhacker@example.net)'
        default: 'autobuild@vyos.net'
        required: true
      BUILD_VERSION:
        description: 'Version number (if empty 1.4-rolling-DATE is used)'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_iso:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume    
      - name: Build
        uses: addnab/docker-run-action@v3
        id: build
        with:
          registry: dockerhub
          image: vyos/vyos-build:current
          options: -v ${{ github.workspace }}:/vyos -w /vyos --privileged
          run: |
            BUILD_BY=${{ github.event.inputs.BUILD_BY }}
            if [ -z $BUILD_BY ]; then
                BUILD_BY="autobuild@vyos.net"
            fi
            BUILD_VERSION=${{ github.event.inputs.BUILD_VERSION }}
            if [ -z $BUILD_VERSION ]; then
                BUILD_VERSION="1.4-rolling-$(date +%Y%m%d%H%M)"
            fi
            IMAGE_NAME="vyos-${BUILD_VERSION}-amd64"
            ISO_IMAGE_NAME="${IMAGE_NAME}.iso"
            echo "::set-output name=IMAGE_NAME::${IMAGE_NAME}"
            echo "::set-output name=ISO_IMAGE_NAME::${ISO_IMAGE_NAME}"
            
            git clone https://github.com/vyos/vyos-build.git
            ls -al
            cd vyos-build
            ./configure --build-by foo \
                        --debian-mirror http://ftp.us.debian.org/debian/ \
                        --build-type release --version ${BUILD_VERSION} \
                        --custom-package vyos-1x-smoketest
            cat /proc/cpuinfo
            sudo dmesg
            sudo make iso
            ls -al build
            env
      
      - name: Archive
        uses: actions/upload-artifact@master            
        with:
          name: ${{ steps.build.outputs.IMAGE_NAME }}
          path: vyos-build/build/${{ steps.build.outputs.ISO_IMAGE_NAME }}
          if-no-files-found: error

      - name: Test ISO
        uses: addnab/docker-run-action@v3
        with:
          registry: dockerhub
          image: vyos/vyos-build:current
          options: -v ${{ github.workspace }}:/vyos -w /vyos --privileged --sysctl net.ipv6.conf.lo.disable_ipv6=0
          run: |
            cd vyos-build
            sudo make testc        
